version: '3.7'
services:
    redis-dev:
        image: redis:6.0
        restart: always
        hostname: redis-host-dev
        networks:
            bridge:
                aliases:
                    - redis-host-dev
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        
        # Saves to disk every 20 seconds (if 1 or more writes done)
        # command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        
        command: redis-server --port ${REDIS_PORT} --loglevel warning --requirepass ${REDIS_PASSWORD}
        environment:
            REDIS_HOST: "${REDIS_HOST}"
            REDIS_PORT: "${REDIS_PORT}"
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            
        # todo-a: start using a cache folder
        # volumes: 
        #     - cache:/data

    mongo-dev: 
        image: mongo:4.0
        hostname: mongo-host-dev
        networks:
            bridge:
                aliases:
                    - mongo-host-dev
       
        volumes:
            - '${MONGO_BASE}/mongodb-data-dev:/data/db'
            - '${MONGOD_CONF}:/etc/mongod.conf'

        command: mongod --config /etc/mongod.conf

        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${mongoPassword}

    # ipfs-dev: 
    #     # https://hub.docker.com/r/ipfs/kubo/
    #     image: ipfs/kubo:release
    #     hostname: ipfs-host-dev
    #     networks:
    #         bridge:
    #             aliases:
    #                 - ipfs-host-dev
    #     deploy:
    #         resources:
    #             limits:
    #                 # Give docker 10% of CPU and 1 GB max
    #                 cpus: "0.1"
    #                 memory: 1000M
    #             # reservations:
    #             #   cpus: 0.25
    #             #   memory: 128M

    #     environment:
    #         # IPFS_PROFILE options (lowpower | server)
    #         IPFS_PROFILE: "server" 
    #         IPFS_PATH: "/data/ipfs"
        
    #     volumes:
    #         - '${ipfs_staging}:/export'
    #         - '${ipfs_data}:/data/ipfs'

    #     ports:
    #         # Allow this thru your firewall: sudo ufw allow 4001
    #         - "4001:4001"
    #         - "4001:4001/udp"

    quanta-dev:
        image: ${DOCKER_IMAGE}
        build: 
            context: .
            args:
                PORT: "${PORT}"
                PORT_DEBUG: "${PORT_DEBUG}"
                JAR_FILE: "${JAR_FILE}"
                XMS: "${XMS}"
                XMX: "${XMX}"
                REDIS_HOST: "${REDIS_HOST}"
                REDIS_PORT: "${REDIS_PORT}"
                REDIS_PASSWORD: "${REDIS_PASSWORD}"
            dockerfile: ./dockerfile-dev
        restart: "no"
        deploy:
            restart_policy:
                condition: none
                max_attempts: 0
            replicas: 1
        hostname: quanta-host
        networks:
            bridge:
                aliases:
                    - quanta-host
        volumes:
            - '${QUANTA_BASE}/tmp:/tmp'
            - '${QUANTA_BASE}/log:/log'
            - '${QUANTA_BASE}/config:/config'
            - '${QUANTA_BASE}/lucene:/subnode-lucene'
            - '${PRJROOT}/src/main/resources/public:/dev-resource-base'
            - '${PRJROOT}/target/classes:/loader-path'
            
        ports:
            - '${HOST_PORT}:${PORT}'
            - '${PORT_DEBUG}:${PORT_DEBUG}'

        environment:
            # Docker warm vars
            X_NODE_ID: "{{.Node.ID}}"
            X_NODE_HOSTNAME: '{{.Node.Hostname}}'
            X_SERVICE_ID: '{{.Service.ID}}'
            X_SERVICE_NAME: '{{.Service.Name}}'
            X_TASK_SLOT: "{{.Task.Slot}}"
            X_TASK_ID: '{{.Task.ID}}'
            X_TASK_NAME: '{{.Task.Name}}'

            logging.config: /log/logback.xml
            XMS: "${XMS}"
            XMX: "${XMX}"

            REDIS_HOST: "${REDIS_HOST}"
            REDIS_PORT: "${REDIS_PORT}"
            REDIS_PASSWORD: "${REDIS_PASSWORD}"
            
            # Can be a comma-delimited list of TestIntf-derived tests to run
            # examples are "LangTest,UtilsTest,MongoTest,MongoFediverseNamesTest,IPFSTest,SchemaOrgTest"
            # **** Tip ****: remember to put this line in setenv-dev.sh if running IPFS tests: `export ipfsEnabled="true"`
            runTests:
            
            adminPassword: "${adminPassword}"
            mongoPassword: "${mongoPassword}"
            mongoSecurity: "true"

            # WARNING: Most browsers (other than Firefox) will not support crypto unless you're on HTTPS
            # requireCrypto: "true"

            # NOTE: '>-' removes all newline characters and makes one long string
            # Using '|' there instead would preserve the newlines after read in
            # The '-' after either of those removes any trailing newline
            testUserAccounts: >-
                FollowBot:${adminPassword}:${devEmail},
                adam:${testPassword}:${devEmail},
                bob:${testPassword}:${devEmail},
                cory:${testPassword}:${devEmail},
                dan:${testPassword}:${devEmail},
                eric:${testPassword}:${devEmail}

            nostrCurationAccounts: >-
                admin,
                bob
    
            testPassword: "${testPassword}"
            throttleTime: "0"
            spring.config.location: "classpath:/application.properties" 
            mongodb.host: "${MONGO_HOST}"
            mongodb.port: "${MONGO_PORT}" 
            instanceId: "dev"
            profileName: "dev"
            server.port: "${PORT}" 
            httpProtocol: "http" 
            metaHost: "${quanta_domain}" 
            allowFileSystemSearch: "false"
            actPubEnabled: "false"

            # tserver-tag
            nostrDaemonEnabled: "${nostrDaemonEnabled}"
            ipfsEnabled: "${ipfsEnabled}"
            spring.http.multipart.max-file-size: "200MB" 
            spring.http.multipart.max-request-size: "200MB" 
            spring.servlet.multipart.max-file-size: "200MB"
            spring.servlet.multipart.max-request-size: "200MB"
            adminDataFolder: "/tmp" 

            # tserver-tag
            TSERVER_PORT: "${TSERVER_PORT}"
            TSERVER_API_KEY: "${TSERVER_API_KEY}"

            mail.port: ""
            mail.user: "postmaster@quantizr.com" 
            mail.password: "${emailPassword}" 
            mail.host: "smtp.mailgun.org" 
            mail.from: "admin@quanta.wiki"

            JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:${PORT_DEBUG},server=y,suspend=n"
            
            ipfs.host: "http://ipfs-host-dev"
            ipfs.apiPort: "5001"
            ipfs.gatewayPort: "8080"

        depends_on:
            - mongo-dev
            - redis-dev
            # - ipfs-dev

    # tserver-tag
    tserver-dev:
        image: ${TSERVER_IMAGE}
        build:
            context: ./src/main/resources/server
            dockerfile: ./dockerfile
        hostname: tserver-host
        networks:
            bridge:
                aliases:
                    - tserver-host
        volumes:
            - '${QUANTA_BASE}/log:/home/node/app/log'
        ports:
            - "${TSERVER_PORT}:${TSERVER_PORT}"
        environment:
            TSERVER_PORT: "${TSERVER_PORT}"
            TSERVER_API_KEY: "${TSERVER_API_KEY}"

networks:
    bridge:
