brandingAppName: Quanta
brandingMetaContent: "Quanta: Social Media Micro-blogging Platform for the Fediverse!"

# Tip: This 'menu' property is seen in TypeScript JSON as an array of objects in 
# variable 'S.quanta.config'
#
# Links here can be full url, or node names, or "tab:tabName"

rhsAnonLinks:
  - name: "About Quanta"
    link: ":home"
  - name: "Explore Features"
    link: ":features"

# These links will show up under MAIN section
# rhsLinks:
#   - name: "separator"
#     link: ""
#   - name: "News"
#     link: ":quanta-news"

systemFolderLinks:
  - name: "User Guide"
    link: ":user-guide"
  - name: "Portal Home"
    link: ":home"

rhsFeedLinks:
  - name: "separator"
    link: ""
  - name: "News"
    link: ":quanta-news"

menu:
  help:
    - name: "About Quanta"
      link: ":home"
    - name: "User Guide"
      link: ":user-guide"

props:
  Person:
    givenName:
      label: "First Name"
      width: 40
      ord: 1
    familyName:
      label: "Last Name"
      width: 60
      ord: 2
    birthDate:
      label: "Birthday"
      width: 80
      ord: 3
      
