# rm -rf .yarn
# rm -rf .node_modules
rm -rf lib
yarn
node build.js

# run TSC to emit types now. (important!)
tsc

# Note: The output TGZ file generated by the 'node pack' command can be used
# so install into other projects just by it's filename like "npm install ${my-tgz-file}"
